anki_deck_name: "01 - vocab::inbox"
anki_model_name: "Japanese Vocab"

field_mapping:
  "~:yk3E2O3Z": "japanese"
  "~:j2NCrJoR": "japanese - note"
  "~:name": "glossary"
  "~:f2ztyGzU": "glossary - note"
